2021-08-23 21:58:45,492 ERROR: Exception on / [GET] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 29, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('explore') }}">Explore</a></li>
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2021-08-23 22:01:32,878 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:47]
2021-08-23 22:01:40,739 ERROR: Exception on / [GET] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 29, in index
    return render_template('index.html', title='Home', posts=posts)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\base.html", line 2, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block "doc"
    {%- block html %}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block "html"
    {% block body -%}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block "body"
    {% block navbar %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\base.html", line 23, in block "navbar"
    <li><a href="{{ url_for('explore') }}">Explore</a></li>
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 356, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2061, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\helpers.py", line 345, in url_for
    force_external=external)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\werkzeug\routing.py", line 2181, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'explore'. Did you mean 'edit_profile' instead?
2021-08-23 22:02:32,005 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:47]
