2021-08-23 20:10:09,649 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 20:10:29,489 ERROR: Exception on /login [POST] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 40, in login
    flask('Invalid username or password')
NameError: name 'flask' is not defined
2021-08-23 20:15:33,866 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 20:15:48,065 ERROR: Exception on /edit_profile [GET] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 81, in edit_profile
    form = EditProfileForm()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\wtforms\form.py", line 212, in __call__
    return type.__call__(cls, *args, **kwargs)
TypeError: __init__() missing 1 required positional argument: 'original_username'
2021-08-23 20:20:38,810 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 20:22:03,454 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 20:23:21,475 ERROR: Exception on /login [POST] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 40, in login
    flask('Invalid username or password')
NameError: name 'flask' is not defined
2021-08-23 20:54:33,332 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 20:54:49,319 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 21:17:10,966 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 21:17:39,341 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 21:18:31,745 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 21:28:36,971 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
2021-08-23 21:32:22,393 ERROR: Exception on /user/Henry [GET] [in c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py:1761]
Traceback (most recent call last):
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\routes.py", line 77, in user
    return render_template('user.html', user=user, posts=posts)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 135, in render_template
    context, ctx.app)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\flask\templating.py", line 117, in _render
    rv = template.render(context)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\templates\user.html", line 17, in block "content"
    {{ form.hidden_tag() }}
  File "c:\users\casan\appdata\local\programs\python\python37-32\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2021-08-23 21:33:53,467 INFO: Microblog startup [in C:\Users\casan\Desktop\Plaque\Commemorative-Plaques-of-UWA\microblog\app\__init__.py:41]
